### PR TITLE
Fix issue 43 implementation

### LINKED ISSUE #43: task subclass not respecting tenants
Should tasks using class based definitions work here?  My tasks using the [Jobtastic baseclass](https://github.com/PolicyStat/jobtastic/blob/master/jobtastic/task.py#L36) do not respect the tenants and always run against the public schema.

I don't see anything related that would cause this, so I am curious if this is expected to work or is a new feature?

### PR DESCRIPTION
**Pull request by thenewguy**
Extends https://github.com/maciej-gol/tenant-schemas-celery/pull/44 with the implementation to fix #43 per https://github.com/maciej-gol/tenant-schemas-celery/issues/43#issuecomment-651956311

### CODE REVIEW

**Comment by thenewguy** [comment]
@maciej-gol do you want the wrapper to appear as a mimic or do you like the "DynamicTenantTask" output for transparency?

**Comment by thenewguy** [comment]
also, are you okay with the test task being a jobtastic task?

**Comment by maciej-gol** [comment]
> @maciej-gol do you want the wrapper to appear as a mimic or do you like the "DynamicTenantTask" output for transparency?

`DynamicTenantTask` is fine!

**Comment by maciej-gol** [comment]
> also, are you okay with the test task being a jobtastic task?

I don't think we need Jobtastic task here. Just any task class that inherits from the generic `Task` should do. Jobtastic is just an implementation detail in the project you are using `tenant-schemas-celery` .

**Comment by thenewguy** [comment]
@maciej-gol turns out Jobtastic task is an old style task class - new style still needs some work. as it seems to require acting on an instance, not the task class.  Haven't fooled with the internals much so going to require some digging.  Do you happen to know if anything special should be done when calling a "new style" task class?  Or just task().delay()?

**Comment by thenewguy** [comment]
odd, build for previous commit ran against 170e1d39af7de9a64c5f29b7b1d8c09727916464 not 7a837ff8925fffd5728736ec8cea63587ea4a704

**Comment by thenewguy** [comment]
So I've hit a snag that I've been trying to work through testing this in the project that prompted the discussion.  The wrapped version of the task doesn't seem to be used.  Not quite sure what the difference is yet, but this still needs some tweaking

The test below that pulls the task from the registry works but the one that uses it directly fails:

```
    def test_tenant_context_for_jobtastic_tasks_from_registry(self):
        # THIS TEST RELIES ON test_jobtastic_task_wrapped ABOVE
        registry = self.CELERY_APP._tasks
        task = registry[JobtasticSchemaTask.name]
        self.assertEqual(task.delay().get(timeout=1), 'test')
        with public_schema_context():
            self.assertEqual(task.delay().get(timeout=1), 'public')
        self.assertEqual(task.delay().get(timeout=1), 'test')
    
    def test_tenant_context_for_jobtastic_tasks(self):
        # THIS TEST RELIES ON test_jobtastic_task_wrapped ABOVE
        self.assertEqual(JobtasticSchemaTask.delay().get(timeout=1), 'test')
        with public_schema_context():
            self.assertEqual(JobtasticSchemaTask.delay().get(timeout=1), 'public')
        self.assertEqual(JobtasticSchemaTask.delay().get(timeout=1), 'test')
```

**Pull request merged**
