### PR TITLE
Fixed async tests

### LINKED ISSUE #20: Test fails when using kombu 4.2.1 and celery 4.2.1
Just to verify this is compatible with latest version of Celery I cloned this repo, created a virtualenv running python `3.6.6` and ran your tests and got this error: 

```
======================================================================
ERROR: test_task_retry (tenant_schemas_celery.tests.CeleryTasksTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/tenant_schemas_celery/tests.py", line 104, in test_task_retry
    update_retry_task.apply_async(args=(self.dummy1.pk, 'updated-name'))
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/tenant_schemas_celery/task.py", line 27, in apply_async
    return super(TenantTask, self).apply_async(args, kwargs, *arg, **kw)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/app/task.py", line 519, in apply_async
    link=link, link_error=link_error, **options)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/tenant_schemas_celery/task.py", line 37, in apply
    return super(TenantTask, self).apply(args, kwargs, *arg, **kw)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/app/task.py", line 736, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/app/trace.py", line 396, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/tenant_schemas_celery/tests.py", line 36, in update_retry_task
    update_retry_task.retry(throw=False)
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/app/task.py", line 677, in retry
    S.apply().get()
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/result.py", line 989, in get
    assert_will_not_block()
  File "/Users/srahmanian/.pyenv/versions/dce/lib/python3.6/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks


----------------------------------------------------------------------
Ran 3 tests in 0.951s
```
Any thoughts?

### PR DESCRIPTION
**Pull request by maciej-gol**
Fixes #20

### CODE REVIEW

**Comment by softinio** [comment]
Thanks for this appreciate it

**Comment by maciej-gol** [comment]
* Have postgresql and rabbitmq running.
* Create a virtualenv and install the requirements.txt file plus the
application.
* Run ./run-tests script inside the virtualenv.

wt., 9 paź 2018 o 00:24 Salar Rahmanian <notifications@github.com>
napisał(a):

**Comment by softinio** [comment]
I get this when I do that any suggestions: 

https://via.softinio.com/Screen-Shot-2018-10-09-13-35-52.png

**Comment by maciej-gol** [comment]
You need to install the package as editable: `pip install -e .` in the
repo's main directory, instead of `pip install .`.

wt., 9 paź 2018 o 22:36 Salar Rahmanian <notifications@github.com>
napisał(a):

**Comment by softinio** [comment]
I did that and got:
```
[2018-10-09 21:05:27,034: INFO/MainProcess] celery@Salars-MacBook-Pro.local ready.
[2018-10-09 21:05:28,639: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[ee7c993f-3dbf-4556-af1d-27066e0e697e]
[2018-10-09 21:05:28,719: ERROR/ForkPoolWorker-8] Task tenant_schemas_celery.test_tasks.update_task[ee7c993f-3dbf-4556-af1d-27066e0e697e] raised unexpected: DoesNotExist()
Traceback (most recent call last):
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 15, in update_task
    dummy = DummyModel.objects.get(pk=model_id)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
test_app.tenant.models.DoesNotExist: DummyModel matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 18, in update_task
    raise DoesNotExist()
tenant_schemas_celery.test_tasks.DoesNotExist
[2018-10-09 21:05:28,777: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[d2442a87-4f13-4b51-9faa-c708ca6d1c82]
[2018-10-09 21:05:28,864: ERROR/ForkPoolWorker-2] Task tenant_schemas_celery.test_tasks.update_task[d2442a87-4f13-4b51-9faa-c708ca6d1c82] raised unexpected: DoesNotExist()
Traceback (most recent call last):
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 15, in update_task
    dummy = DummyModel.objects.get(pk=model_id)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
test_app.tenant.models.DoesNotExist: DummyModel matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 18, in update_task
    raise DoesNotExist()
tenant_schemas_celery.test_tasks.DoesNotExist
[2018-10-09 21:05:28,870: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[f6ca56bd-01c9-4b7d-97df-407789379929]
[2018-10-09 21:05:28,976: INFO/ForkPoolWorker-4] Task tenant_schemas_celery.test_tasks.update_task[f6ca56bd-01c9-4b7d-97df-407789379929] succeeded in 0.1042454260023078s: None
.[2018-10-09 21:05:29,131: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_retry_task[610a014c-3e1a-42cc-915b-eb6e1653faf5]
[2018-10-09 21:05:29,209: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_retry_task[610a014c-3e1a-42cc-915b-eb6e1653faf5]  ETA:[2018-10-09 21:05:29.291796+00:00]
[2018-10-09 21:05:29,211: INFO/ForkPoolWorker-6] Task tenant_schemas_celery.test_tasks.update_retry_task[610a014c-3e1a-42cc-915b-eb6e1653faf5] retry: Retry in 0.1s
[2018-10-09 21:05:31,062: INFO/ForkPoolWorker-8] Task tenant_schemas_celery.test_tasks.update_retry_task[610a014c-3e1a-42cc-915b-eb6e1653faf5] succeeded in 0.03211822199227754s: None
.[2018-10-09 21:05:31,132: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[823360bd-555d-42c0-81c0-1ad2df5c141c]
[2018-10-09 21:05:31,181: INFO/ForkPoolWorker-2] Task tenant_schemas_celery.test_tasks.update_task[823360bd-555d-42c0-81c0-1ad2df5c141c] succeeded in 0.04838212201138958s: None
[2018-10-09 21:05:31,185: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[2dfab23c-bb84-4be0-b76d-13fa58f583f5]
[2018-10-09 21:05:31,220: INFO/ForkPoolWorker-4] Task tenant_schemas_celery.test_tasks.update_task[2dfab23c-bb84-4be0-b76d-13fa58f583f5] succeeded in 0.03493194699694868s: None
[2018-10-09 21:05:31,228: INFO/MainProcess] Received task: tenant_schemas_celery.test_tasks.update_task[223b052d-e985-4288-a395-0b0391065f7f]
[2018-10-09 21:05:31,250: ERROR/ForkPoolWorker-6] Task tenant_schemas_celery.test_tasks.update_task[223b052d-e985-4288-a395-0b0391065f7f] raised unexpected: DoesNotExist()
Traceback (most recent call last):
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 15, in update_task
    dummy = DummyModel.objects.get(pk=model_id)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
test_app.tenant.models.DoesNotExist: DummyModel matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/srahmanian/.pyenv/versions/3.6.6/envs/tsc/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/srahmanian/experiments/tenant-schemas-celery/tenant_schemas_celery/test_tasks.py", line 18, in update_task
    raise DoesNotExist()
tenant_schemas_celery.test_tasks.DoesNotExist
```
weird !

**Comment by maciej-gol** [comment]
As long as the tests pass, it is ok. The tests are also testing retrying
and similar scenarios, which include raising an exception and checking if
the schema is changed in the retried task.

wt., 9 paź 2018 o 23:07 Salar Rahmanian <notifications@github.com>
napisał(a):

**Comment by softinio** [comment]
Oh got it I didn't notice they had passed but they had. Thanks again dude.

**Pull request merged**
